// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh6X2vfm0O5voAPlMXYR1IXjDYZhDSLVU',
    appId: '1:139903145543:web:55adc9c7cda8890e5f8362',
    messagingSenderId: '139903145543',
    projectId: 'chatapp-4ac4a',
    authDomain: 'chatapp-4ac4a.firebaseapp.com',
    storageBucket: 'chatapp-4ac4a.firebasestorage.app',
    measurementId: 'G-TZ21JBR7XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SlL0bpAOsE9hMb9eV-pxoOYdvsf0F9w',
    appId: '1:139903145543:android:fa82384297b964085f8362',
    messagingSenderId: '139903145543',
    projectId: 'chatapp-4ac4a',
    storageBucket: 'chatapp-4ac4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9poD2-D8ZEPTZDr702aJ6oWycL5x9LqQ',
    appId: '1:139903145543:ios:b21749b31206b4555f8362',
    messagingSenderId: '139903145543',
    projectId: 'chatapp-4ac4a',
    storageBucket: 'chatapp-4ac4a.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9poD2-D8ZEPTZDr702aJ6oWycL5x9LqQ',
    appId: '1:139903145543:ios:b21749b31206b4555f8362',
    messagingSenderId: '139903145543',
    projectId: 'chatapp-4ac4a',
    storageBucket: 'chatapp-4ac4a.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh6X2vfm0O5voAPlMXYR1IXjDYZhDSLVU',
    appId: '1:139903145543:web:55adc9c7cda8890e5f8362',
    messagingSenderId: '139903145543',
    projectId: 'chatapp-4ac4a',
    authDomain: 'chatapp-4ac4a.firebaseapp.com',
    storageBucket: 'chatapp-4ac4a.firebasestorage.app',
    measurementId: 'G-TZ21JBR7XH',
  );
}
